services:
  caldera:
    build:
      context: ./caldera-src
      dockerfile: Dockerfile
    container_name: caldera_server
    restart: always
    ports:
      - "8889:8888" # Web UI
      - "8443:8443" # HTTPS Web UI
      - "7010:7010" # Agent communication
      - "7011:7011" # Agent communication
      - "7012:7012" # Agent communication
    volumes:
      - caldera_data:/usr/src/app/data

volumes:
  caldera_data:
