apiVersion: v1
kind: Service
metadata:
  name: wazuh-syslog-bridge
  namespace: falco
  annotations:
    argos-lab.io/purpose: "Bridge Falcosidekick syslog hacia el host Docker Desktop/WSL2"
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: syslog-udp
      port: 514
      protocol: UDP
